package main

import (
	"bytes"
	"fmt"
	"go/format"
)

func generateContracts(target sdkTarget) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by vzbridgegen; DO NOT EDIT.\n//go:build darwin && %s\n\npackage vzbridge\n\nvar sdkContracts = []sdkMethodContract{\n", target.Architecture)
	for _, m := range target.Methods {
		if len(m.Unsupported) != 0 {
			continue
		}
		fmt.Fprintf(&out, "{Owner:%q, Selector:%q, GoName:%q, Introduced:%q, Obsoleted:%q, Category:%q, Instance:%t, Factory:%t, ResultABI:%q, Parameters:[]string{", m.Owner, m.Selector, m.GoName, m.Introduced, m.Obsoleted, m.Category, m.Instance, m.Factory, m.Result.ABI)
		for _, p := range m.Parameters {
			fmt.Fprintf(&out, "%q,", p.Type.ABI)
		}
		fmt.Fprintln(&out, "}},")
	}
	fmt.Fprintln(&out, "}")
	return format.Source(out.Bytes())
}
