package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

func signature(call checkedOperation) string {
	var p []string
	for i, argument := range call.Parameters {
		name := fmt.Sprintf("p%d", i)
		p = append(p, name+" "+argument.Go)
	}
	return strings.Join(p, ", ")
}

func bindings(calls []checkedOperation, hash [4]uint64, arch string, sdkVersion int) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by vzbridgegen; DO NOT EDIT.\n//go:build darwin && %s\n\npackage vzbridge\n\n", arch)
	fmt.Fprintf(&b, "/*\n#cgo LDFLAGS: ${SRCDIR}/abi_%s/libBridge.a -L/usr/lib/swift -framework Foundation -framework Virtualization -framework Cocoa ${SRCDIR}/abi_%s/Virtualization.tbd\n#include <stdint.h>\n#include <stdbool.h>\nuint64_t vz_bridge_abi(uint32_t index);\n", arch, arch)
	for _, call := range calls {
		var parameters []string
		for i, p := range call.Parameters {
			parameters = append(parameters, fmt.Sprintf("%s p%d", p.C, i))
		}
		if len(parameters) == 0 {
			parameters = append(parameters, "void")
		}
		fmt.Fprintf(&b, "%s %s(%s);\n", call.Result.C, call.Symbol, strings.Join(parameters, ", "))
	}
	b.WriteString("*/\nimport \"C\"\n\nimport (\"sync\";\"github.com/ebitengine/purego\";\n")
	writeTypeImports(&b, calls)
	fmt.Fprintf(&b, ")\n\nconst SDKVersion = %d\n\n", sdkVersion)
	b.WriteString("func init(){\nvar abi func(uint32)uint64\npurego.RegisterFunc(&abi,uintptr(C.vz_bridge_abi))\n")
	fmt.Fprintf(&b, "expected:=[4]uint64{%d,%d,%d,%d}\n", hash[0], hash[1], hash[2], hash[3])
	b.WriteString("for i,want:=range expected{if abi(uint32(i))!=want{panic(\"vz: bridge ABI mismatch\")}}\n")
	b.WriteString("}\n\n")

	for i, call := range calls {
		var abiArgs []string
		for _, p := range call.Parameters {
			abiArgs = append(abiArgs, p.ABI)
		}
		fmt.Fprintf(&b, "var native%d struct {once sync.Once;call func(%s) %s}\n\n", i, strings.Join(abiArgs, ","), call.Result.ABI)
		p := signature(call)
		fmt.Fprintf(&b, "func %s(%s) %s {\n", call.Name, p, call.Result.Go)
		fmt.Fprintf(&b, "native%d.once.Do(func(){purego.RegisterFunc(&native%d.call,uintptr(C.%s))})\n", i, i, call.Symbol)
		var args []string
		for j, a := range call.Parameters {
			name := fmt.Sprintf("p%d", j)
			if a.Role == "object" {
				args = append(args, "objc.Ptr("+name+")")
			} else {
				args = append(args, name)
			}
		}
		if call.Result.Go != "" {
			b.WriteString("result := ")
		}
		fmt.Fprintf(&b, "native%d.call(%s)\n", i, strings.Join(args, ","))
		switch call.Result.Role {
		case "owned":
			b.WriteString("value:=objc.NewManagedPointer(result,ReleaseObject)\n")
		}
		for j, a := range call.Parameters {
			if a.Role == "object" || a.Role == "cstring" {
				fmt.Fprintf(&b, "runtime.KeepAlive(p%d)\n", j)
			}
		}
		if call.Result.Go != "" {
			if call.Result.Role == "owned" {
				b.WriteString("return value\n")
			} else {
				b.WriteString("return result\n")
			}
		}
		b.WriteString("}\n\n")
	}

	return format.Source(b.Bytes())
}

func writeTypeImports(b *bytes.Buffer, calls []checkedOperation) {
	usesObjc, usesUnsafe, usesRuntime := false, false, false
	for _, call := range calls {
		values := []valueType{call.Result}
		for _, p := range call.Parameters {
			values = append(values, p.valueType)
			usesRuntime = usesRuntime || p.Role == "object" || p.Role == "cstring"
		}
		for _, v := range values {
			usesObjc = usesObjc || strings.Contains(v.Go, "objc.")
			usesUnsafe = usesUnsafe || strings.Contains(v.Go, "unsafe.") || strings.Contains(v.ABI, "unsafe.")
		}
	}
	if usesObjc {
		b.WriteString("\"github.com/Code-Hex/vz/v3/internal/objc\"\n")
	}
	if usesUnsafe {
		b.WriteString("\"unsafe\"\n")
	}
	if usesRuntime {
		b.WriteString("\"runtime\"\n")
	}
}
