package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

func generateSDK(target sdkTarget) ([]byte, error) {
	if target.Architecture != "arm64" && target.Architecture != "amd64" {
		return nil, fmt.Errorf("unsupported architecture %q", target.Architecture)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by vzbridgegen from the macOS SDK; DO NOT EDIT.\n//go:build darwin && %s\n\npackage vzbridge\n\nimport (\"runtime\";\"unsafe\";\"github.com/Code-Hex/vz/v3/internal/objc\"; runtimeobjc \"github.com/ebitengine/purego/objc\")\n\n", target.Architecture)
	for _, enum := range target.Enums {
		for _, v := range enum.Values {
			fmt.Fprintf(&b, "const %s = %s\n", v.Name, v.Value)
		}
	}
	names := map[string]bool{}
	for _, m := range target.Methods {
		if len(m.Unsupported) > 0 {
			continue
		}
		if names[m.GoName] {
			return nil, fmt.Errorf("duplicate generated name %s", m.GoName)
		}
		names[m.GoName] = true
		if !validSDKType(m.Result, true) {
			return nil, fmt.Errorf("unknown ABI in %s", m.ID)
		}
		var native, parameters, args, alive []string
		native = append(native, "unsafe.Pointer", "runtimeobjc.SEL")
		if m.Instance && !m.Factory {
			parameters = append(parameters, "receiver objc.NSObject")
			alive = append(alive, "receiver")
		}
		for i, p := range m.Parameters {
			name := fmt.Sprintf("p%d", i)
			if !validSDKType(p.Type, false) {
				return nil, fmt.Errorf("unknown parameter ABI in %s", m.ID)
			}
			parameters = append(parameters, name+" "+p.Type.Go)
			native = append(native, p.Type.ABI)
			arg := name
			if p.Type.Kind == "object" {
				arg = "objc.Ptr(" + name + ")"
			}
			args = append(args, arg)
			if p.Type.Kind != "scalar" && p.Type.Kind != "enum" {
				alive = append(alive, name)
			}
		}
		signature := fmt.Sprintf("func(%s) %s", strings.Join(native, ", "), m.Result.ABI)
		fmt.Fprintf(&b, "var sdkCall%s lazyBinding[directBinding[%s]]\n", m.GoName, signature)
		fmt.Fprintf(&b, "func %s(%s) %s {\n", m.GoName, strings.Join(parameters, ", "), m.Result.Go)
		fmt.Fprintf(&b, "binding := sdkCall%s.get(func() directBinding[%s] { return bindDirect[%s](%q) })\n", m.GoName, signature, signature, m.Selector)
		if m.Result.Go != "" {
			fmt.Fprintf(&b, "var result %s\n", m.Result.ABI)
		}
		fmt.Fprintln(&b, "onQueue(func(){")
		recv := "directClass(" + fmt.Sprintf("%q", m.Owner) + ")"
		if m.Instance && !m.Factory {
			recv = "objc.Ptr(receiver)"
		}
		if m.Factory {
			recv = "directAllocate(" + recv + ")"
		}
		if m.Factory {
			fmt.Fprintf(&b, "sdkRequireVersion(%q,%q,%q)\n", m.GoName, m.Introduced, m.Obsoleted)
			fmt.Fprintf(&b, "allocated := %s\n", recv)
			recv = "allocated"
		}
		if m.Factory {
			fmt.Fprintf(&b, "sdkRequireInitializer(%q,%q,%q,%q,%s)\n", m.Owner, m.Selector, m.Introduced, m.Obsoleted, recv)
		} else if m.Instance {
			fmt.Fprintf(&b, "sdkRequire(%q,%q,%q,%q,true,%s)\n", m.Owner, m.Selector, m.Introduced, m.Obsoleted, recv)
		} else {
			fmt.Fprintf(&b, "sdkRequire(%q,%q,%q,%q,false)\n", m.Owner, m.Selector, m.Introduced, m.Obsoleted)
		}
		for i, p := range m.Parameters {
			if p.Type.Kind == "error-out" {
				fmt.Fprintf(&b, "if p%d != nil {*p%d = nil}\n", i, i)
			}
		}
		if m.Result.Go != "" {
			fmt.Fprint(&b, "result = ")
		}
		fmt.Fprintf(&b, "binding.call(%s, binding.selector", recv)
		for _, arg := range args {
			fmt.Fprintf(&b, ", %s", arg)
		}
		fmt.Fprintln(&b, ")")
		if m.Result.Kind == "object" && m.Ownership == "borrowed" {
			fmt.Fprintln(&b, "result = directRetain(result)")
		}
		for i, p := range m.Parameters {
			if p.Type.Kind == "error-out" {
				fmt.Fprintf(&b, "if p%d != nil {*p%d = directRetain(*p%d)}\n", i, i, i)
			}
		}
		fmt.Fprintln(&b, "})")
		for _, arg := range alive {
			fmt.Fprintf(&b, "runtime.KeepAlive(%s)\n", arg)
		}
		if m.Result.Kind == "object" {
			fmt.Fprintln(&b, "return objc.NewManagedPointer(result, ReleaseObject)")
		} else if m.Result.Go != "" {
			fmt.Fprintln(&b, "return result")
		}
		fmt.Fprintln(&b, "}")
	}
	for _, m := range target.Methods {
		if len(m.Unsupported) > 0 {
			fmt.Fprintf(&b, "// Unsupported %s: %s\n", m.ID, strings.Join(m.Unsupported, "; "))
		}
	}
	return format.Source(b.Bytes())
}

func validSDKType(t sdkType, result bool) bool {
	scalar := func(value string) bool {
		for _, abi := range scalarABI {
			if abi == value && abi != "" {
				return true
			}
		}
		return false
	}
	switch t.Kind {
	case "scalar":
		return t.ABI == t.Go && (scalar(t.ABI) || (result && t.ABI == ""))
	case "enum":
		return t.ABI == t.Go && scalar(t.ABI) && t.ABI != "bool" && t.ABI != "float32" && t.ABI != "float64"
	case "object":
		expected := "objc.NSObject"
		if result {
			expected = "*objc.Pointer"
		}
		return t.ABI == "unsafe.Pointer" && t.Go == expected && t.Class != ""
	case "class":
		return t.ABI == "unsafe.Pointer" && t.Go == t.ABI
	case "pointer":
		return t.ABI == t.Go && (t.ABI == "unsafe.Pointer" || strings.HasPrefix(t.ABI, "*") && scalar(t.ABI[1:]))
	case "cstring":
		return t.ABI == "string" && t.Go == t.ABI
	case "error-out":
		return !result && t.ABI == "*unsafe.Pointer" && t.Go == t.ABI
	}
	return false
}
