package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

type privateMetadata struct {
	Architecture string
	OSVersion    string
	Methods      []privateMethod
}
type privateMethod struct {
	Class       string
	Image       string
	Selector    string
	ClassMethod bool
	Result      string
	Arguments   []string
}
type privateReport struct {
	HostArchitecture   string
	HostOSVersion      string
	TargetArchitecture string
	Discovered         int
	Generated          int
	Unsupported        []string
}

func discoverPrivate(temp string) (privateMetadata, error) {
	var metadata privateMetadata
	directory, err := os.MkdirTemp(temp, "vz-private-")
	if err != nil {
		return metadata, err
	}
	defer os.RemoveAll(directory)
	source := filepath.Join(directory, "inspect.m")
	binary := filepath.Join(directory, "inspect")
	if err = os.WriteFile(source, []byte(privateInspector), 0600); err != nil {
		return metadata, err
	}
	if output, err := exec.Command("xcrun", "clang", "-fobjc-arc", "-framework", "Foundation", "-framework", "Virtualization", source, "-o", binary).CombinedOutput(); err != nil {
		return metadata, fmt.Errorf("compile runtime inspector: %w: %s", err, output)
	}
	output, err := exec.Command(binary).Output()
	if err != nil {
		return metadata, fmt.Errorf("inspect runtime: %w", err)
	}
	if err = json.Unmarshal(output, &metadata); err != nil {
		return metadata, fmt.Errorf("decode runtime metadata: %w", err)
	}
	if metadata.Architecture != runtime.GOARCH {
		return metadata, fmt.Errorf("runtime architecture %q differs from generator host %s", metadata.Architecture, runtime.GOARCH)
	}
	return metadata, nil
}

func privateType(encoding string) (string, error) {
	original := encoding
	encoding = strings.TrimLeft(encoding, "rnNoORV")
	switch encoding {
	case "v":
		return "", nil
	case "B":
		return "bool", nil
	case "c":
		return "int8", nil
	case "C":
		return "uint8", nil
	case "s":
		return "int16", nil
	case "S":
		return "uint16", nil
	case "i", "l":
		return "int32", nil
	case "I", "L":
		return "uint32", nil
	case "q":
		return "int64", nil
	case "Q":
		return "uint64", nil
	case "f":
		return "float32", nil
	case "d":
		return "float64", nil
	case "@", "#", ":", "*":
		return "unsafe.Pointer", nil
	case "@?":
		return "", fmt.Errorf("block requires a native callback adapter")
	}
	if strings.HasPrefix(encoding, "@\"") && strings.HasSuffix(encoding, "\"") {
		return "unsafe.Pointer", nil
	}
	if strings.HasPrefix(encoding, "^") && len(encoding) > 1 && !strings.Contains(encoding, "?") {
		return "unsafe.Pointer", nil
	}
	return "", fmt.Errorf("unsupported runtime type encoding %q", original)
}

func privateBindingName(method privateMethod) string {
	kind := "Instance"
	if method.ClassMethod {
		kind = "Class"
	}
	hash := sha256.Sum256([]byte(method.Class + "/" + kind + "/" + method.Selector))
	name := strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			return r
		}
		return '_'
	}, method.Class+"_"+kind+"_"+method.Selector)
	return fmt.Sprintf("UnsafePrivate_%s_%x", name, hash[:4])
}

func generatePrivate(metadata privateMetadata, arch string) ([]byte, privateReport, error) {
	report := privateReport{HostArchitecture: metadata.Architecture, HostOSVersion: metadata.OSVersion, TargetArchitecture: arch, Discovered: len(metadata.Methods)}
	if arch != "arm64" && arch != "amd64" {
		return nil, report, fmt.Errorf("unsupported architecture %q", arch)
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by vzbridgegen. DO NOT EDIT.\n// Host runtime: %s %s.\n// The host method census is shared across targets; each call checks the local runtime ABI.\n// Unsafe callers must establish fixed arity, argument lifetimes, and ownership.\n// Runtime encodings do not record variadic declarations or ownership attributes.\n// For object results, retainResult adds a retain before the queue's pool drains.\n// Callers release owned results and any requested retain; invoked distinguishes a rejected call.\n//go:build darwin && %s\n\npackage vzbridge\n\n", metadata.Architecture, strings.ReplaceAll(metadata.OSVersion, "\n", " "), arch)
	methods := append([]privateMethod(nil), metadata.Methods...)
	sort.Slice(methods, func(i, j int) bool { return privateBindingName(methods[i]) < privateBindingName(methods[j]) })
	var body strings.Builder
	seen := map[string]bool{}
	for _, method := range methods {
		name := privateBindingName(method)
		if seen[name] {
			return nil, report, fmt.Errorf("duplicate runtime method %s", name)
		}
		seen[name] = true
		code, err := generatePrivateMethod(method, name)
		if err != nil {
			kind := "-"
			if method.ClassMethod {
				kind = "+"
			}
			report.Unsupported = append(report.Unsupported, fmt.Sprintf("%s %s %s: %v", method.Class, kind, method.Selector, err))
			continue
		}
		body.WriteString(code)
		report.Generated++
	}
	if report.Generated > 0 {
		out.WriteString("import (\"unsafe\"; runtimeobjc \"github.com/ebitengine/purego/objc\")\n\n")
	}
	out.WriteString(body.String())
	for _, reason := range report.Unsupported {
		fmt.Fprintf(&out, "// Unsupported %s\n", reason)
	}
	code, err := format.Source([]byte(out.String()))
	return code, report, err
}

func generatePrivateMethod(method privateMethod, name string) (string, error) {
	if len(method.Arguments) < 2 || method.Arguments[0] != "@" || method.Arguments[1] != ":" || strings.Count(method.Selector, ":") != len(method.Arguments)-2 {
		return "", fmt.Errorf("invalid runtime method signature")
	}
	if len(method.Arguments) > 15 {
		return "", fmt.Errorf("more than 15 native arguments")
	}
	result, err := privateType(method.Result)
	if err != nil {
		return "", err
	}
	native := []string{"unsafe.Pointer", "runtimeobjc.SEL"}
	var params, args []string
	if !method.ClassMethod {
		params = append(params, "receiver unsafe.Pointer")
	}
	for i, encoding := range method.Arguments[2:] {
		typ, err := privateType(encoding)
		if err != nil {
			return "", fmt.Errorf("argument %d: %w", i, err)
		}
		if typ == "" {
			return "", fmt.Errorf("argument %d has void encoding", i)
		}
		arg := fmt.Sprintf("p%d", i)
		native = append(native, typ)
		params = append(params, arg+" "+typ)
		args = append(args, arg)
	}
	objectEncoding := strings.TrimLeft(method.Result, "rnNoORV")
	objectResult := objectEncoding == "@" || strings.HasPrefix(objectEncoding, "@\"")
	if objectResult {
		params = append(params, "retainResult bool", "invoked unsafe.Pointer")
	}
	signature := "func(" + strings.Join(native, ", ") + ") " + result
	var out strings.Builder
	fmt.Fprintf(&out, "var privateCall%s lazyBinding[directBinding[%s]]\n", name, signature)
	fmt.Fprintf(&out, "func %s(%s) %s {\n", name, strings.Join(params, ", "), result)
	if result != "" {
		fmt.Fprintf(&out, "var result %s\n", result)
	}
	out.WriteString("onQueue(func(){\n")
	if objectResult {
		out.WriteString("if invoked != nil { *(*bool)(invoked) = false }\n")
	}
	fmt.Fprintf(&out, "binding := privateCall%s.get(func() directBinding[%s] { return bindDirect[%s](%q) })\n", name, signature, signature, method.Selector)
	if method.ClassMethod {
		fmt.Fprintf(&out, "receiver := directGetClass(%q)\n", method.Class)
	}
	fmt.Fprintf(&out, "if !privateAvailable(receiver, %q, binding.selector, %t, %q, %#v) {\n", method.Class, method.ClassMethod, method.Result, method.Arguments)
	if objectResult {
		out.WriteString("if invoked != nil { return }\n")
	}
	fmt.Fprintf(&out, "panic(%q)\n}\n", "private method unavailable or ABI changed: "+method.Class+" "+method.Selector)
	if objectResult {
		out.WriteString("if invoked != nil { *(*bool)(invoked) = true }\n")
	}
	if result != "" {
		out.WriteString("result = ")
	}
	fmt.Fprintf(&out, "binding.call(%s)\n", strings.Join(append([]string{"receiver", "binding.selector"}, args...), ", "))
	if objectResult {
		out.WriteString("if retainResult && result != nil { result = directRetain(result) }\n")
	}
	out.WriteString("})\n")
	if result != "" {
		out.WriteString("return result\n")
	}
	out.WriteString("}\n\n")
	return out.String(), nil
}

const privateInspector = `
#import <Foundation/Foundation.h>
#import <Virtualization/Virtualization.h>
#import <objc/runtime.h>

int main(void) {
 @autoreleasepool {
  const char *image = class_getImageName([VZVirtualMachineConfiguration class]);
  if (image == NULL) return 1;
  unsigned count = 0;
  const char **names = objc_copyClassNamesForImage(image, &count);
  NSMutableArray *methods = [NSMutableArray array];
  for (unsigned i = 0; i < count; i++) {
   Class cls = objc_getClass(names[i]);
   for (int classMethod = 0; classMethod < 2; classMethod++) {
    unsigned methodCount = 0;
    Method *list = class_copyMethodList(classMethod ? object_getClass(cls) : cls, &methodCount);
    for (unsigned j = 0; j < methodCount; j++) {
     Method method = list[j];
     char *result = method_copyReturnType(method);
     NSMutableArray *arguments = [NSMutableArray array];
     for (unsigned k = 0; k < method_getNumberOfArguments(method); k++) {
      char *argument = method_copyArgumentType(method, k);
      [arguments addObject:argument ? @(argument) : @"?"];
      free(argument);
     }
     [methods addObject:@{@"Class":@(names[i]), @"Image":@(image), @"Selector":@(sel_getName(method_getName(method))), @"ClassMethod":classMethod ? @YES : @NO, @"Result":result ? @(result) : @"?", @"Arguments":arguments}];
     free(result);
    }
    free(list);
   }
  }
  free(names);
#if defined(__arm64__)
  NSString *architecture = @"arm64";
#elif defined(__x86_64__)
  NSString *architecture = @"amd64";
#else
#error Unsupported architecture
#endif
  NSDictionary *metadata = @{@"Architecture":architecture, @"OSVersion":NSProcessInfo.processInfo.operatingSystemVersionString, @"Methods":methods};
  NSError *error = nil;
  NSData *data = [NSJSONSerialization dataWithJSONObject:metadata options:0 error:&error];
  if (data == nil) return 1;
  [NSFileHandle.fileHandleWithStandardOutput writeData:data];
 }
 return 0;
}
`
