package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type privateMetadata struct {
	Architecture string          `json:"architecture"`
	OSVersion    string          `json:"osVersion"`
	Methods      []privateMethod `json:"methods"`
}

type privateMethod struct {
	Class       string   `json:"class"`
	Image       string   `json:"image"`
	Selector    string   `json:"selector"`
	ClassMethod bool     `json:"classMethod"`
	Result      string   `json:"result"`
	Arguments   []string `json:"arguments"`
}

func discoverPrivate(temp string, classes []string) (privateMetadata, error) {
	var metadata privateMetadata
	directory, err := os.MkdirTemp(temp, "private-discovery-")
	if err != nil {
		return metadata, err
	}
	defer os.RemoveAll(directory)
	source := filepath.Join(directory, "Inspect.swift")
	if err := os.WriteFile(source, []byte(privateInspector), 0600); err != nil {
		return metadata, err
	}
	binary := filepath.Join(directory, "inspect")
	if _, err := command("xcrun", "swiftc", "-swift-version", "6", "-strict-concurrency=complete", "-warnings-as-errors", "-module-cache-path", filepath.Join(directory, "cache"), source, "-o", binary); err != nil {
		return metadata, err
	}
	arguments := append([]string(nil), classes...)
	sort.Strings(arguments)
	data, err := command(binary, arguments...)
	if err != nil {
		return metadata, err
	}
	if err := json.Unmarshal(data, &metadata); err != nil {
		return metadata, fmt.Errorf("private framework metadata: %w", err)
	}
	return metadata, nil
}

func privateSwiftType(encoding string) (string, error) {
	encoding = strings.TrimLeft(encoding, "rnNoORV")
	if encoding == "#" || encoding == ":" || encoding == "*" || strings.HasPrefix(encoding, "^") && !strings.Contains(encoding, "?") || strings.HasPrefix(encoding, "@\"") && strings.HasSuffix(encoding, "\"") {
		return "UnsafeMutableRawPointer?", nil
	}
	types := map[string]string{"v": "Void", "@": "UnsafeMutableRawPointer?", "B": "Bool", "c": "Int8", "C": "UInt8", "s": "Int16", "S": "UInt16", "i": "Int32", "I": "UInt32", "l": "Int32", "L": "UInt32", "q": "Int64", "Q": "UInt64", "f": "Float", "d": "Double"}
	if result, ok := types[encoding]; ok {
		return result, nil
	}
	return "", fmt.Errorf("unsupported runtime type encoding %q", encoding)
}

func privateBindingName(method privateMethod) string {
	kind := "Instance"
	if method.ClassMethod {
		kind = "Class"
	}
	key := method.Class + "/" + kind + "/" + method.Selector
	hash := sha256.Sum256([]byte(key))
	name := strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			return r
		}
		return '_'
	}, method.Class+"_"+kind+"_"+method.Selector)
	return fmt.Sprintf("UnsafePrivate_%s_%x", name, hash[:4])
}

func generatePrivate(metadata privateMetadata) ([]byte, []operation, []string, error) {
	var out strings.Builder
	out.WriteString("// Code generated by vzbridgegen. DO NOT EDIT.\nimport Foundation\nimport Virtualization\nimport ObjectiveC\n\n")
	out.WriteString(privateRuntime)
	operations := []operation{{Name: "UnsafePrivateAllocate", Symbol: "vz_UnsafePrivateAllocate", Parameters: map[string]string{"className": "cstring"}, Result: "raw"}}
	var unsupported []string
	methods := append([]privateMethod(nil), metadata.Methods...)
	sort.Slice(methods, func(i, j int) bool { return privateBindingName(methods[i]) < privateBindingName(methods[j]) })
	names := map[string]bool{}
	for _, method := range methods {
		name := privateBindingName(method)
		if names[name] {
			return nil, nil, nil, fmt.Errorf("duplicate private export %q", name)
		}
		names[name] = true
		code, contract, err := generatePrivateMethod(method, name)
		if err != nil {
			unsupported = append(unsupported, fmt.Sprintf("%s %s: %v", method.Class, method.Selector, err))
			continue
		}
		out.WriteString(code)
		operations = append(operations, contract)
	}
	return []byte(out.String()), operations, unsupported, nil
}

func generatePrivateMethod(method privateMethod, name string) (string, operation, error) {
	contract := operation{Symbol: "vz_" + name, Name: name, Parameters: map[string]string{}}
	if len(method.Arguments) < 2 || method.Arguments[0] != "@" || method.Arguments[1] != ":" || strings.Count(method.Selector, ":") != len(method.Arguments)-2 {
		return "", contract, fmt.Errorf("invalid runtime method signature")
	}
	result, err := privateSwiftType(method.Result)
	if err != nil {
		return "", contract, err
	}
	var parameters, types, arguments []string
	receiverType, receiver := "UnsafeMutableRawPointer?", "receiver"
	if method.ClassMethod {
		receiverType, receiver = "AnyClass", "cls"
	} else {
		parameters = append(parameters, "_ receiver: UnsafeMutableRawPointer?")
		contract.Parameters["receiver"] = "raw"
	}
	types = append(types, receiverType, "Selector")
	arguments = append(arguments, receiver, "selector")
	for i, encoding := range method.Arguments[2:] {
		native, err := privateSwiftType(encoding)
		if err != nil || native == "Void" {
			return "", contract, fmt.Errorf("argument %d has unsupported runtime encoding %q", i, encoding)
		}
		argument := fmt.Sprintf("arg%d", i)
		parameters = append(parameters, "_ "+argument+": "+native)
		types = append(types, native)
		arguments = append(arguments, argument)
		if native == "UnsafeMutableRawPointer?" {
			contract.Parameters[argument] = "raw"
		}
	}
	if result == "UnsafeMutableRawPointer?" {
		contract.Result = "raw"
	}
	objectResult := strings.TrimLeft(method.Result, "rnNoORV")
	retainsObject := objectResult == "@" || strings.HasPrefix(objectResult, "@\"")
	if retainsObject {
		parameters = append(parameters, "_ retainResult: Bool", "_ invoked: UnsafeMutablePointer<Bool>?")
		contract.Parameters["invoked"] = "raw"
	}
	if len(parameters) > 15 {
		return "", contract, fmt.Errorf("more than 15 bridge arguments")
	}
	var encoded []string
	for _, argument := range method.Arguments {
		encoded = append(encoded, strconv.Quote(argument))
	}
	var out strings.Builder
	fmt.Fprintf(&out, "\n@c(%s)\npublic func %s(%s) -> %s {\n    bridgeSync {\n", contract.Symbol, name, strings.Join(parameters, ", "), result)
	if retainsObject {
		out.WriteString("        invoked?.pointee = false\n")
	}
	fmt.Fprintf(&out, "        let selector = NSSelectorFromString(%s)\n", strconv.Quote(method.Selector))
	fmt.Fprintf(&out, "        guard let cls = NSClassFromString(%s)", strconv.Quote(method.Class))
	lookup := "cls"
	if !method.ClassMethod {
		out.WriteString(", let receiver, let actualClass = privateBridgeReceiverClass(receiver, cls)")
		lookup = "actualClass"
	}
	fmt.Fprintf(&out, ",\n              let method = privateBridgeMethod(%s, selector, %t, %s, [%s]) else {\n", lookup, method.ClassMethod, strconv.Quote(method.Result), strings.Join(encoded, ", "))
	if retainsObject {
		out.WriteString("            if invoked != nil { return nil }\n")
	}
	fmt.Fprintf(&out, "            preconditionFailure(%s)\n", strconv.Quote("private method unavailable or ABI changed: "+method.Class+" "+method.Selector))
	out.WriteString("        }\n")
	fmt.Fprintf(&out, "        typealias Invoke = @convention(c) (%s) -> %s\n        let invoke = unsafeBitCast(method_getImplementation(method), to: Invoke.self)\n", strings.Join(types, ", "), result)
	if retainsObject {
		fmt.Fprintf(&out, "        invoked?.pointee = true\n        guard let result = invoke(%s) else { return nil }\n        if retainResult {\n            _ = Unmanaged<AnyObject>.fromOpaque(result).retain()\n        }\n        return result\n", strings.Join(arguments, ", "))
	} else {
		fmt.Fprintf(&out, "        return invoke(%s)\n", strings.Join(arguments, ", "))
	}
	out.WriteString("    }\n}\n")
	return out.String(), contract, nil
}

const privateRuntime = `
nonisolated private let privateBridgeObjectClass = unsafeBitCast(dlsym(UnsafeMutableRawPointer(bitPattern: -2), "object_getClass")!, to: (@convention(c) (UnsafeMutableRawPointer?) -> AnyClass?).self)

func privateBridgeReceiverClass(_ receiver: UnsafeMutableRawPointer, _ expected: AnyClass) -> AnyClass? {
    guard let actual = privateBridgeObjectClass(receiver) else { return nil }
    var current: AnyClass? = actual
    while let cls = current {
        if ObjectIdentifier(cls) == ObjectIdentifier(expected) { return actual }
        current = class_getSuperclass(cls)
    }
    return nil
}

func privateBridgeMethod(_ cls: AnyClass, _ selector: Selector, _ classMethod: Bool, _ result: String, _ arguments: [String]) -> Method? {
    guard let method = classMethod ? class_getClassMethod(cls, selector) : class_getInstanceMethod(cls, selector), method_getNumberOfArguments(method) == arguments.count else { return nil }
    let returnType = method_copyReturnType(method)
    defer { free(returnType) }
    guard String(cString: returnType) == result else { return nil }
    for (index, expected) in arguments.enumerated() {
        guard let argument = method_copyArgumentType(method, UInt32(index)) else { return nil }
        defer { free(argument) }
        guard String(cString: argument) == expected else { return nil }
    }
    return method
}

@c(vz_UnsafePrivateAllocate)
public func UnsafePrivateAllocate(_ className: UnsafePointer<CChar>?) -> UnsafeMutableRawPointer? {
    bridgeSync {
        guard let className, let cls = NSClassFromString(String(cString: className)) else { return nil }
        let selector = NSSelectorFromString("alloc")
        guard let method = privateBridgeMethod(cls, selector, true, "@", ["@", ":"]) else { return nil }
        let invoke = unsafeBitCast(method_getImplementation(method), to: (@convention(c) (AnyClass, Selector) -> UnsafeMutableRawPointer?).self)
        return invoke(cls, selector)
    }
}
`

const privateInspector = `import Foundation
import Virtualization
import ObjectiveC

struct MethodInfo: Encodable {
    var ` + "`class`" + `: String
    var image: String
    var selector: String
    var classMethod: Bool
    var result: String
    var arguments: [String]
}
struct Metadata: Encodable {
    var architecture: String
    var osVersion: String
    var methods: [MethodInfo]
}
#if arch(arm64)
let architecture = "arm64"
#elseif arch(x86_64)
let architecture = "amd64"
#else
#error("Unsupported architecture")
#endif
let frameworkImage = String(cString: class_getImageName(VZVirtualMachineConfiguration.self)!)
var classes = Array(CommandLine.arguments.dropFirst())
let includeInherited = !classes.isEmpty
if classes.isEmpty {
    var count: UInt32 = 0
    if let list = objc_copyClassNamesForImage(frameworkImage, &count) {
        defer { free(list) }
        for index in 0..<Int(count) {
            classes.append(String(cString: list[index]))
        }
    }
}
var methods: [MethodInfo] = []
for name in classes.sorted() {
    guard let cls = NSClassFromString(name) else {
        FileHandle.standardError.write(Data("Missing class: \(name)\n".utf8))
        exit(1)
    }
    let image = class_getImageName(cls).map { String(cString: $0) } ?? ""
    for classMethod in [false, true] {
        var current: AnyClass? = classMethod ? object_getClass(cls) : cls
        var seen = Set<String>()
        while let type = current {
            var count: UInt32 = 0
            if let list = class_copyMethodList(type, &count) {
                defer { free(list) }
                for index in 0..<Int(count) {
                    let method = list[index]
                    let selector = NSStringFromSelector(method_getName(method))
                    if !seen.insert(selector).inserted { continue }
                    let result = method_copyReturnType(method)
                    defer { free(result) }
                    let arguments = (0..<method_getNumberOfArguments(method)).map { index -> String in
                        guard let value = method_copyArgumentType(method, index) else { return "?" }
                        defer { free(value) }
                        return String(cString: value)
                    }
                    methods.append(MethodInfo(class: name, image: image, selector: selector, classMethod: classMethod, result: String(cString: result), arguments: arguments))
                }
            }
            current = includeInherited ? class_getSuperclass(type) : nil
        }
    }
}
methods.sort { ($0.class, $0.classMethod ? 1 : 0, $0.selector) < ($1.class, $1.classMethod ? 1 : 0, $1.selector) }
let metadata = Metadata(architecture: architecture, osVersion: ProcessInfo.processInfo.operatingSystemVersionString, methods: methods)
FileHandle.standardOutput.write(try JSONEncoder().encode(metadata))
`
