package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func publishBuild(temp, output string) error {
	names := []string{"abi_arm64/libBridge.a", "abi_amd64/libBridge.a", "abi_arm64/Virtualization.tbd", "abi_amd64/Virtualization.tbd", "binding_arm64.go", "binding_amd64.go", "abi_arm64/Framework.swift", "abi_amd64/Framework.swift"}
	for _, name := range names {
		path := filepath.Join(output, name)
		info, err := os.Lstat(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("refusing to replace %s", path)
		}
		if strings.HasSuffix(name, ".go") || strings.HasSuffix(name, ".swift") {
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !strings.HasPrefix(string(data), "// Code generated by vzbridgegen; DO NOT EDIT.") {
				return fmt.Errorf("refusing to replace handwritten %s", path)
			}
		}
	}
	for _, name := range names {
		path := filepath.Join(output, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		if err := os.Rename(filepath.Join(temp, name), path); err != nil {
			return err
		}
	}
	return nil
}
