// Code generated by nativegen; DO NOT EDIT.
//go:build darwin

package vzbridge

/*
#include "native.h"
*/
import "C"

import (
	"runtime"
	"unsafe"

	"github.com/Code-Hex/vz/v4/internal/objc"
	"github.com/ebitengine/purego"
)

var callAttachDeviceVZUSBController lazyBinding[func(unsafe.Pointer, unsafe.Pointer, uint64)]

func AttachDeviceVZUSBController(p0 objc.NSObject, p1 objc.NSObject, p2 uint64) {
	call := callAttachDeviceVZUSBController.get(func() func(unsafe.Pointer, unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_attachDeviceVZUSBController))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), objc.Ptr(p1), p2)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
}

var callCancelInstallVZMacOSInstaller lazyBinding[func(unsafe.Pointer)]

func CancelInstallVZMacOSInstaller(p0 objc.NSObject) {
	call := callCancelInstallVZMacOSInstaller.get(func() func(unsafe.Pointer) {
		var call func(unsafe.Pointer)
		purego.RegisterFunc(&call, uintptr(C.vz_cancelInstallVZMacOSInstaller))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
}

var callDetachDeviceVZUSBController lazyBinding[func(unsafe.Pointer, unsafe.Pointer, uint64)]

func DetachDeviceVZUSBController(p0 objc.NSObject, p1 objc.NSObject, p2 uint64) {
	call := callDetachDeviceVZUSBController.get(func() func(unsafe.Pointer, unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_detachDeviceVZUSBController))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), objc.Ptr(p1), p2)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
}

var callDispatchQueuePointer lazyBinding[func() unsafe.Pointer]

func DispatchQueuePointer() unsafe.Pointer {
	call := callDispatchQueuePointer.get(func() func() unsafe.Pointer {
		var call func() unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_dispatchQueuePointer))
		return call
	})
	var result unsafe.Pointer
	result = call()
	return result
}

var callDrain lazyBinding[func()]

func Drain() {
	call := callDrain.get(func() func() { var call func(); purego.RegisterFunc(&call, uintptr(C.vz_drain)); return call })
	call()
}

var callFetchLatestSupportedMacOSRestoreImageWithCompletionHandler lazyBinding[func(uint64)]

func FetchLatestSupportedMacOSRestoreImageWithCompletionHandler(p0 uint64) {
	call := callFetchLatestSupportedMacOSRestoreImageWithCompletionHandler.get(func() func(uint64) {
		var call func(uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_fetchLatestSupportedMacOSRestoreImageWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(p0)
	})
}

var callGetUUIDUSBDevice lazyBinding[func(unsafe.Pointer) unsafe.Pointer]

func GetUUIDUSBDevice(p0 objc.NSObject) *objc.Pointer {
	call := callGetUUIDUSBDevice.get(func() func(unsafe.Pointer) unsafe.Pointer {
		var call func(unsafe.Pointer) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_getUUIDUSBDevice))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callInstallByVZMacOSInstaller lazyBinding[func(unsafe.Pointer, uint64, uint64)]

func InstallByVZMacOSInstaller(p0 objc.NSObject, p1 uint64, p2 uint64) {
	call := callInstallByVZMacOSInstaller.get(func() func(unsafe.Pointer, uint64, uint64) {
		var call func(unsafe.Pointer, uint64, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_installByVZMacOSInstaller))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1, p2)
	})
	runtime.KeepAlive(p0)
}

var callInvalidateVZVirtioSocketListener lazyBinding[func(unsafe.Pointer)]

func InvalidateVZVirtioSocketListener(p0 objc.NSObject) {
	call := callInvalidateVZVirtioSocketListener.get(func() func(unsafe.Pointer) {
		var call func(unsafe.Pointer)
		purego.RegisterFunc(&call, uintptr(C.vz_invalidateVZVirtioSocketListener))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
}

var callLinuxInstallRosetta lazyBinding[func(uint64)]

func LinuxInstallRosetta(p0 uint64) {
	call := callLinuxInstallRosetta.get(func() func(uint64) {
		var call func(uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_linuxInstallRosetta))
		return call
	})
	onQueue(func() {
		call(p0)
	})
}

var callLoadMacOSRestoreImageFile lazyBinding[func(string, uint64)]

func LoadMacOSRestoreImageFile(p0 string, p1 uint64) {
	call := callLoadMacOSRestoreImageFile.get(func() func(string, uint64) {
		var call func(string, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_loadMacOSRestoreImageFile))
		return call
	})
	onQueue(func() {
		call(p0, p1)
	})
	runtime.KeepAlive(p0)
}

var callMacOSRestoreImageMajorVersion lazyBinding[func(unsafe.Pointer) int64]

func MacOSRestoreImageMajorVersion(p0 objc.NSObject) int64 {
	call := callMacOSRestoreImageMajorVersion.get(func() func(unsafe.Pointer) int64 {
		var call func(unsafe.Pointer) int64
		purego.RegisterFunc(&call, uintptr(C.vz_macOSRestoreImageMajorVersion))
		return call
	})
	var result int64
	onQueue(func() {
		result = call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
	return result
}

var callMacOSRestoreImageMinorVersion lazyBinding[func(unsafe.Pointer) int64]

func MacOSRestoreImageMinorVersion(p0 objc.NSObject) int64 {
	call := callMacOSRestoreImageMinorVersion.get(func() func(unsafe.Pointer) int64 {
		var call func(unsafe.Pointer) int64
		purego.RegisterFunc(&call, uintptr(C.vz_macOSRestoreImageMinorVersion))
		return call
	})
	var result int64
	onQueue(func() {
		result = call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
	return result
}

var callMacOSRestoreImagePatchVersion lazyBinding[func(unsafe.Pointer) int64]

func MacOSRestoreImagePatchVersion(p0 objc.NSObject) int64 {
	call := callMacOSRestoreImagePatchVersion.get(func() func(unsafe.Pointer) int64 {
		var call func(unsafe.Pointer) int64
		purego.RegisterFunc(&call, uintptr(C.vz_macOSRestoreImagePatchVersion))
		return call
	})
	var result int64
	onQueue(func() {
		result = call(objc.Ptr(p0))
	})
	runtime.KeepAlive(p0)
	return result
}

var callSetInvalidDiskModeError lazyBinding[func(*unsafe.Pointer)]

func SetInvalidDiskModeError(errorOut *unsafe.Pointer) {
	call := callSetInvalidDiskModeError.get(func() func(*unsafe.Pointer) {
		var call func(*unsafe.Pointer)
		purego.RegisterFunc(&call, uintptr(C.vz_setInvalidDiskModeError))
		return call
	})
	onQueue(func() {
		call(errorOut)
	})
	runtime.KeepAlive(errorOut)
}

var callNewVZDiskBlockDeviceStorageDeviceAttachment lazyBinding[func(int32, bool, int32, *unsafe.Pointer) unsafe.Pointer]

func NewVZDiskBlockDeviceStorageDeviceAttachment(p0 int32, p1 bool, p2 int32, p3 *unsafe.Pointer) *objc.Pointer {
	call := callNewVZDiskBlockDeviceStorageDeviceAttachment.get(func() func(int32, bool, int32, *unsafe.Pointer) unsafe.Pointer {
		var call func(int32, bool, int32, *unsafe.Pointer) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZDiskBlockDeviceStorageDeviceAttachment))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(p0, p1, p2, p3)
	})
	runtime.KeepAlive(p3)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZFileHandleNetworkDeviceAttachment lazyBinding[func(int32, *unsafe.Pointer) unsafe.Pointer]

func NewVZFileHandleNetworkDeviceAttachment(p0 int32, p1 *unsafe.Pointer) *objc.Pointer {
	call := callNewVZFileHandleNetworkDeviceAttachment.get(func() func(int32, *unsafe.Pointer) unsafe.Pointer {
		var call func(int32, *unsafe.Pointer) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZFileHandleNetworkDeviceAttachment))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(p0, p1)
	})
	runtime.KeepAlive(p1)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZFileHandleSerialPortAttachment lazyBinding[func(int32, int32, *unsafe.Pointer) unsafe.Pointer]

func NewVZFileHandleSerialPortAttachment(p0 int32, p1 int32, p2 *unsafe.Pointer) *objc.Pointer {
	call := callNewVZFileHandleSerialPortAttachment.get(func() func(int32, int32, *unsafe.Pointer) unsafe.Pointer {
		var call func(int32, int32, *unsafe.Pointer) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZFileHandleSerialPortAttachment))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(p0, p1, p2)
	})
	runtime.KeepAlive(p2)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZMacOSInstaller lazyBinding[func(unsafe.Pointer, string) unsafe.Pointer]

func NewVZMacOSInstaller(p0 objc.NSObject, p1 string) *objc.Pointer {
	call := callNewVZMacOSInstaller.get(func() func(unsafe.Pointer, string) unsafe.Pointer {
		var call func(unsafe.Pointer, string) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZMacOSInstaller))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZNetworkBlockDeviceStorageDeviceAttachment lazyBinding[func(string, float64, bool, int32, *unsafe.Pointer, uint64) unsafe.Pointer]

func NewVZNetworkBlockDeviceStorageDeviceAttachment(p0 string, p1 float64, p2 bool, p3 int32, p4 *unsafe.Pointer, p5 uint64) *objc.Pointer {
	call := callNewVZNetworkBlockDeviceStorageDeviceAttachment.get(func() func(string, float64, bool, int32, *unsafe.Pointer, uint64) unsafe.Pointer {
		var call func(string, float64, bool, int32, *unsafe.Pointer, uint64) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZNetworkBlockDeviceStorageDeviceAttachment))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(p0, p1, p2, p3, p4, p5)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p4)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZVirtioSocketListener lazyBinding[func(uint64) unsafe.Pointer]

func NewVZVirtioSocketListener(p0 uint64) *objc.Pointer {
	call := callNewVZVirtioSocketListener.get(func() func(uint64) unsafe.Pointer {
		var call func(uint64) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZVirtioSocketListener))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(p0)
	})
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callNewVZVirtualMachineWithDispatchQueue lazyBinding[func(unsafe.Pointer, uint64, uint64) unsafe.Pointer]

func NewVZVirtualMachineWithDispatchQueue(p0 objc.NSObject, p1 uint64, p2 uint64) *objc.Pointer {
	call := callNewVZVirtualMachineWithDispatchQueue.get(func() func(unsafe.Pointer, uint64, uint64) unsafe.Pointer {
		var call func(unsafe.Pointer, uint64, uint64) unsafe.Pointer
		purego.RegisterFunc(&call, uintptr(C.vz_newVZVirtualMachineWithDispatchQueue))
		return call
	})
	var result unsafe.Pointer
	onQueue(func() {
		result = call(objc.Ptr(p0), p1, p2)
	})
	runtime.KeepAlive(p0)
	return objc.NewManagedPointer(result, ReleaseObject)
}

var callPauseWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64)]

func PauseWithCompletionHandler(p0 objc.NSObject, p1 uint64) {
	call := callPauseWithCompletionHandler.get(func() func(unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_pauseWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
}

var callReleaseObject lazyBinding[func(unsafe.Pointer)]

func ReleaseObject(p0 unsafe.Pointer) {
	call := callReleaseObject.get(func() func(unsafe.Pointer) {
		var call func(unsafe.Pointer)
		purego.RegisterFunc(&call, uintptr(C.vz_releaseObject))
		return call
	})
	call(p0)
	runtime.KeepAlive(p0)
}

var callRestoreMachineStateFromURLWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64, string)]

func RestoreMachineStateFromURLWithCompletionHandler(p0 objc.NSObject, p1 uint64, p2 string) {
	call := callRestoreMachineStateFromURLWithCompletionHandler.get(func() func(unsafe.Pointer, uint64, string) {
		var call func(unsafe.Pointer, uint64, string)
		purego.RegisterFunc(&call, uintptr(C.vz_restoreMachineStateFromURLWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1, p2)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p2)
}

var callResumeWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64)]

func ResumeWithCompletionHandler(p0 objc.NSObject, p1 uint64) {
	call := callResumeWithCompletionHandler.get(func() func(unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_resumeWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
}

var callSaveMachineStateToURLWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64, string)]

func SaveMachineStateToURLWithCompletionHandler(p0 objc.NSObject, p1 uint64, p2 string) {
	call := callSaveMachineStateToURLWithCompletionHandler.get(func() func(unsafe.Pointer, uint64, string) {
		var call func(unsafe.Pointer, uint64, string)
		purego.RegisterFunc(&call, uintptr(C.vz_saveMachineStateToURLWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1, p2)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p2)
}

var callSetCallback lazyBinding[func(uint64)]

func SetCallback(p0 uint64) {
	call := callSetCallback.get(func() func(uint64) {
		var call func(uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_setCallback))
		return call
	})
	onQueue(func() {
		call(p0)
	})
}

var callSocketConnectionDuplicatedFileDescriptor lazyBinding[func(unsafe.Pointer, *unsafe.Pointer) int32]

func SocketConnectionDuplicatedFileDescriptor(p0 objc.NSObject, p1 *unsafe.Pointer) int32 {
	call := callSocketConnectionDuplicatedFileDescriptor.get(func() func(unsafe.Pointer, *unsafe.Pointer) int32 {
		var call func(unsafe.Pointer, *unsafe.Pointer) int32
		purego.RegisterFunc(&call, uintptr(C.vz_socketConnectionDuplicatedFileDescriptor))
		return call
	})
	var result int32
	onQueue(func() {
		result = call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
	return result
}

var callStartVirtualMachineWindow lazyBinding[func(unsafe.Pointer, unsafe.Pointer, float64, float64, string, bool)]

func StartVirtualMachineWindow(p0 objc.NSObject, p1 unsafe.Pointer, p2 float64, p3 float64, p4 string, p5 bool) {
	call := callStartVirtualMachineWindow.get(func() func(unsafe.Pointer, unsafe.Pointer, float64, float64, string, bool) {
		var call func(unsafe.Pointer, unsafe.Pointer, float64, float64, string, bool)
		purego.RegisterFunc(&call, uintptr(C.vz_startVirtualMachineWindow))
		return call
	})
	call(objc.Ptr(p0), p1, p2, p3, p4, p5)
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
	runtime.KeepAlive(p4)
}

var callStartWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64)]

func StartWithCompletionHandler(p0 objc.NSObject, p1 uint64) {
	call := callStartWithCompletionHandler.get(func() func(unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_startWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
}

var callStartWithOptionsCompletionHandler lazyBinding[func(unsafe.Pointer, unsafe.Pointer, uint64)]

func StartWithOptionsCompletionHandler(p0 objc.NSObject, p1 objc.NSObject, p2 uint64) {
	call := callStartWithOptionsCompletionHandler.get(func() func(unsafe.Pointer, unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_startWithOptionsCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), objc.Ptr(p1), p2)
	})
	runtime.KeepAlive(p0)
	runtime.KeepAlive(p1)
}

var callStopWithCompletionHandler lazyBinding[func(unsafe.Pointer, uint64)]

func StopWithCompletionHandler(p0 objc.NSObject, p1 uint64) {
	call := callStopWithCompletionHandler.get(func() func(unsafe.Pointer, uint64) {
		var call func(unsafe.Pointer, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_stopWithCompletionHandler))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1)
	})
	runtime.KeepAlive(p0)
}

var callVZVirtioSocketDevice_connectToPort lazyBinding[func(unsafe.Pointer, uint32, uint64)]

func VZVirtioSocketDevice_connectToPort(p0 objc.NSObject, p1 uint32, p2 uint64) {
	call := callVZVirtioSocketDevice_connectToPort.get(func() func(unsafe.Pointer, uint32, uint64) {
		var call func(unsafe.Pointer, uint32, uint64)
		purego.RegisterFunc(&call, uintptr(C.vz_VZVirtioSocketDevice_connectToPort))
		return call
	})
	onQueue(func() {
		call(objc.Ptr(p0), p1, p2)
	})
	runtime.KeepAlive(p0)
}
