package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	input := flag.String("input", "../../cmd/vzbridgegen/metadata/native.json", "saved generation metadata")
	header := flag.String("header", "native.h", "native bridge header")
	output := flag.String("output", "native_bindings.go", "generated Go output file")
	extract := flag.Bool("extract", false, "refresh metadata from the header without generating code")
	flag.Parse()
	if err := run(*input, *header, *output, *extract); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(input, header, output string, extract bool) error {
	if extract {
		return extractMetadata(input, header)
	}
	metadata, err := readMetadata(input, header)
	if err != nil {
		return err
	}
	source, err := generate(metadata.Bindings)
	if err != nil {
		return err
	}
	return os.WriteFile(output, source, 0644)
}

func generate(bindings []binding) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by nativegen; DO NOT EDIT.\n//go:build darwin\n\npackage vzbridge\n\n/*\n#include \"native.h\"\n*/\nimport \"C\"\n\nimport (\"runtime\"\n \"unsafe\"\n\n \"github.com/Code-Hex/vz/v3/internal/objc\"\n \"github.com/ebitengine/purego\")")
	for _, b := range bindings {
		var params, types, args []string
		for _, p := range b.Parameters {
			params = append(params, p.Name+" "+p.Type)
			typ := p.Type
			arg := p.Name
			if typ == "objc.NSObject" {
				typ = "unsafe.Pointer"
				arg = "objc.Ptr(" + arg + ")"
			}
			types = append(types, typ)
			args = append(args, arg)
		}
		nativeResult := b.Result
		if nativeResult == "*objc.Pointer" {
			nativeResult = "unsafe.Pointer"
		}
		signature := fmt.Sprintf("func(%s) %s", strings.Join(types, ", "), nativeResult)
		fmt.Fprintf(&out, "\nvar call%s lazyBinding[%s]\n", b.Name, signature)
		fmt.Fprintf(&out, "func %s(%s) %s {\n", b.Name, strings.Join(params, ", "), b.Result)
		fmt.Fprintf(&out, "call := call%s.get(func() %s { var call %s; purego.RegisterFunc(&call, uintptr(C.%s)); return call })\n", b.Name, signature, signature, b.Symbol)
		if b.Result != "" {
			fmt.Fprintf(&out, "var result %s\n", nativeResult)
		}
		if b.Queue {
			fmt.Fprintln(&out, "onQueue(func() {")
		}
		if b.Result != "" {
			fmt.Fprint(&out, "result = ")
		}
		fmt.Fprintf(&out, "call(%s)\n", strings.Join(args, ", "))
		if b.Queue {
			fmt.Fprintln(&out, "})")
		}
		for _, p := range b.Parameters {
			if p.Type == "objc.NSObject" || p.Type == "unsafe.Pointer" || p.Type == "*unsafe.Pointer" || p.Type == "string" {
				fmt.Fprintf(&out, "runtime.KeepAlive(%s)\n", p.Name)
			}
		}
		if b.Result == "*objc.Pointer" {
			fmt.Fprintln(&out, "return objc.NewManagedPointer(result, ReleaseObject)")
		} else if b.Result != "" {
			fmt.Fprintln(&out, "return result")
		}
		fmt.Fprintln(&out, "}")
	}
	return format.Source(out.Bytes())
}
